swagger: 2.0
info:
  title: Aquo API
  version: 1.0
host: localhost
basePath: /api/aquo
produces:
  - application/json
paths:
  /search/begrippen/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchConceptenData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - begrip
              - begrip_label
              - synoniem
              - definitie 
              - categorie_begrip 
              - categorie_begrip_label 
              - found
            items:
              type: object
              properties:
                begrip:
                  type: string
                  format: string
                begrip_label:
                  type: string
                  format: string
                synoniem:
                  type: string
                  format: string
                definitie:
                  type: string
                  format: string
                categorie_begrip:
                  type: string
                  format: string
                categorie_begrip_label:
                  type: string
                  format: string
                found:
                  type: string
                  format: string       
  /search/categorieen/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchCategorieenData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - ?categorie 
              - ?categorie_label 
            items:
              type: object
              properties:
                categorie:
                  type: string
                  format: string
                categorie_label:
                  type: string
                  format: string
                  /search/categorieen/{term}:
  /search/domeintabellen/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchDomeinenData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - ?domeintabel 
              - ?domeintabel_label 
            items:
              type: object
              properties:
                domeintabel:
                  type: string
                  format: string
                domeintabel_label:
                  type: string
                  format: string
  /search/domeinwaarden/{term}:
    get:
      x-dotwebstack-information-product: "http://dotwebstack.org/configuration/SearchDomeinWaardeData"
      parameters:
        - name: term
          in: path
          description: search term 
          required: true
          type: string  
          x-dotwebstack-parameter: "http://dotwebstack.org/configuration/TermParameter"          
      responses:
        200:
          description: OK
          schema:
            type: array
            required:
              - label_waarde
              - domeintabel_waarde
              - domeintabel_waarde_label
              - CASnummer 
              - Code 
              - ID 
              - gevonden_in
            items:
              type: object
              properties:
                label_waarde:
                  type: string
                  format: string
                domeintabel_waarde:
                  type: string
                  format: string
                domeintabel_waarde_label:
                  type: string
                  format: string
                CASnummer:
                  type: string
                  format: string
                Code:
                  type: string
                  format: string
                ID:
                  type: string
                  format: string
                gevonden_in:
                  type: string
                  format: string
                

                