spring:
  main:
    banner-mode: "off"
  jersey:
    type: filter
  resources:
    static-locations: file:./static/,classpath:/static/

logging.level:
  org.dotwebstack.framework: INFO
  org.dotwebstack.ldtlegacy: INFO
  org.springframework.boot.autoconfigure.logging: INFO
  org.eclipse.rdf4j: INFO

dotwebstack:
  config:
    aquoroot:
    resourcePath: file:../../LDTBasisconfig/config
    host: localhost
    port: 8080
    linkstrategy: local
    systemGraph: http://dotwebstack.org/configuration/Theatre
    shacl:
      uri:
        result:
          path: http://www.w3.org/ns/shacl#resultPath
          message:

security:
  authentication: form
  loginPage: /login
  users:
    - user: beheerder
      password: $2a$11$Z0uBLK6ocuMoqVYFUimZre./Y4iBq5v8IrhOVpR.oVJzJK6V7.lVu
      role: admin
  protect:
    - path: /beheer/**
      role: admin
